requires 'Data::Pageset';
requires 'DateTime';
requires 'Digest::MD5';
requires 'Email::Sender';
requires 'Email::Simple';
requires 'Email::Valid';
requires 'Encode';
requires 'HTTP::CookieJar';
requires 'HTTP::Tiny';
requires 'Mojolicious';
requires 'Mojolicious::Plugin::Number::Commify';
requires 'Parcel::Track';
requires 'Path::Tiny';
requires 'String::Random';

# cpan.theopencloset.net
requires 'OpenCloset::Common';
requires 'OpenCloset::Plugin::Helpers';
requires 'OpenCloset::Schema';
